apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
spec:
  ports:
  - name: {{ .Release.Name }}-web
    port: 80
  selector:
    app: {{ .Release.Name }}-deployment
  type: ClusterIP
